In [1]:
import pandas as pd

In [2]:
df_main=pd.read_csv('../Dataset/main.csv')
df_main

,RID,PTID,VISCODE,SITE,COLPROT,ORIGPROT,EXAMDATE,DX.bl,AGE,PTGENDER,...,EcogSPOrgan.bl,EcogSPDivatt.bl,EcogSPTotal.bl,FDG.bl,PIB.bl,AV45.bl,Years.bl,Month.bl,Month,M
0,2,011_S_0002,bl,11,ADNI1,ADNI1,2005-09-08,CN,74.3,Male,...,NaN,NaN,NaN,6.846324,NaN,NaN,0.000000,0.000000,0.0,0
1,2,011_S_0002,m06,11,ADNI1,ADNI1,2006-03-06,CN,74.3,Male,...,NaN,NaN,NaN,6.846324,NaN,NaN,0.490075,5.868852,6.0,6
2,2,011_S_0002,m36,11,ADNI1,ADNI1,2008-08-27,CN,74.3,Male,...,NaN,NaN,NaN,6.846324,NaN,NaN,2.967830,35.540984,36.0,36
3,2,011_S_0002,m60,11,ADNIGO,ADNI1,2010-09-22,CN,74.3,Male,...,NaN,NaN,NaN,6.846324,NaN,NaN,5.037645,60.327869,60.0,60
4,2,011_S_0002,m66,11,ADNIGO,ADNI1,2011-03-04,CN,74.3,Male,...,NaN,NaN,NaN,6.846324,NaN,NaN,5.483915,65.672131,66.0,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11144,5292,057_S_5292,m06,57,ADNI2,ADNI2,2014-05-08,SMC,74.3,Female,...,1.000000,1.25,1.289474,7.157804,NaN,1.373677,0.484600,5.803279,6.0,6
11145,5294,051_S_5294,bl,51,ADNI2,ADNI2,2013-11-25,SMC,68.5,Male,...,1.000000,1.00,1.000000,6.980701,NaN,NaN,0.000000,0.000000,0.0,0
11146,5295,057_S_5295,bl,57,ADNI2,ADNI2,2013-12-11,SMC,75.5,Female,...,1.800000,1.50,1.578947,5.815852,NaN,NaN,0.000000,0.000000,0.0,0
11147,5295,057_S_5295,m03,57,ADNI2,ADNI2,2014-02-14,SMC,75.5,Female,...,1.800000,1.50,1.578947,5.815852,NaN,NaN,0.177960,2.131148,3.0,3
11148,5296,053_S_5296,bl,53,ADNI2,ADNI2,2013-12-18,SMC,69.3,Male,...,1.333333,1.75,1.461538,7.146315,NaN,NaN,0.000000,0.000000,0.0,0

In [5]:
df_main.columns

Index(['RID', 'PTID', 'VISCODE', 'SITE', 'COLPROT', 'ORIGPROT', 'EXAMDATE',
       'DX.bl', 'AGE', 'PTGENDER', 'PTEDUCAT', 'PTETHCAT', 'PTRACCAT',
       'PTMARRY', 'APOE4', 'FDG', 'PIB', 'AV45', 'CDRSB', 'ADAS11', 'ADAS13',
       'MMSE', 'RAVLT.immediate', 'RAVLT.learning', 'RAVLT.forgetting',
       'RAVLT.perc.forgetting', 'FAQ', 'MOCA', 'EcogPtMem', 'EcogPtLang',
       'EcogPtVisspat', 'EcogPtPlan', 'EcogPtOrgan', 'EcogPtDivatt',
       'EcogPtTotal', 'EcogSPMem', 'EcogSPLang', 'EcogSPVisspat', 'EcogSPPlan',
       'EcogSPOrgan', 'EcogSPDivatt', 'EcogSPTotal', 'Ventricles',
       'Hippocampus', 'WholeBrain', 'Entorhinal', 'Fusiform', 'MidTemp', 'ICV',
       'DX', 'EXAMDATE.bl', 'CDRSB.bl', 'ADAS11.bl', 'ADAS13.bl', 'MMSE.bl',
       'RAVLT.immediate.bl', 'RAVLT.learning.bl', 'RAVLT.forgetting.bl',
       'RAVLT.perc.forgetting.bl', 'FAQ.bl', 'Ventricles.bl', 'Hippocampus.bl',
       'WholeBrain.bl', 'Entorhinal.bl', 'Fusiform.bl', 'MidTemp.bl', 'ICV.bl',
       'MOCA.bl', 'EcogPtMem.bl', 'EcogPtLang.bl', 'EcogPtVisspat.bl',
       'EcogPtPlan.bl', 'EcogPtOrgan.bl', 'EcogPtDivatt.bl', 'EcogPtTotal.bl',
       'EcogSPMem.bl', 'EcogSPLang.bl', 'EcogSPVisspat.bl', 'EcogSPPlan.bl',
       'EcogSPOrgan.bl', 'EcogSPDivatt.bl', 'EcogSPTotal.bl', 'FDG.bl',
       'PIB.bl', 'AV45.bl', 'Years.bl', 'Month.bl', 'Month', 'M'],
      dtype='object')

In [7]:
df_main.dtypes

RID           int64
PTID         object
VISCODE      object
SITE          int64
COLPROT      object
             ...
AV45.bl     float64
Years.bl    float64
Month.bl    float64
Month       float64
M             int64
Length: 89, dtype: object

In [12]:
df_main.describe()

,RID,SITE,AGE,PTEDUCAT,APOE4,FDG,PIB,AV45,CDRSB,ADAS11,...,EcogSPOrgan.bl,EcogSPDivatt.bl,EcogSPTotal.bl,FDG.bl,PIB.bl,AV45.bl,Years.bl,Month.bl,Month,M
count,11149.000000,11149.000000,11149.000000,11149.000000,10689.000000,3245.000000,224.000000,1427.000000,7608.000000,7642.000000,...,4367.000000,4474.000000,4569.000000,7743.000000,133.000000,4444.000000,11149.000000,11149.000000,11147.000000,11149.000000
mean,2084.674500,72.672885,74.004826,15.962418,0.542801,6.040951,1.782857,1.194378,2.118494,11.557608,...,1.650733,1.848011,1.698366,6.212210,1.605639,1.196505,1.849353,22.146766,22.083789,21.943134
std,1819.238884,106.660123,6.958396,2.846152,0.656943,0.803906,0.421587,0.225827,2.618455,8.603207,...,0.842256,0.900323,0.710641,0.729958,0.314547,0.219669,1.929719,23.109174,23.068866,22.896261
min,2.000000,2.000000,48.100000,4.000000,0.000000,3.184009,1.095000,0.826002,0.000000,0.000000,...,1.000000,1.000000,1.000000,3.486321,1.155000,0.826002,-0.503765,-6.032787,0.000000,0.000000
25%,558.000000,21.000000,70.000000,14.000000,0.000000,5.548492,1.361875,1.008418,0.000000,5.670000,...,1.000000,1.000000,1.153846,5.765617,1.360000,1.013022,0.476386,5.704918,6.000000,6.000000
50%,1190.000000,41.000000,74.000000,16.000000,0.000000,6.097610,1.848750,1.115761,1.000000,9.000000,...,1.250000,1.500000,1.435897,6.249237,1.567500,1.121655,1.207392,14.459016,12.000000,12.000000
75%,4237.000000,116.000000,79.000000,18.000000,1.000000,6.568940,2.127500,1.370745,3.000000,15.000000,...,2.000000,2.500000,2.052632,6.681914,1.835000,1.367395,2.527036,30.262295,30.000000,30.000000
max,5296.000000,941.000000,91.400000,20.000000,2.000000,8.766609,2.927500,2.055796,18.000000,70.000000,...,4.000000,4.000000,3.948718,8.535850,2.282500,1.969645,8.520192,102.032787,102.000000,102.000000

In [14]:
df_main.isnull().sum()

RID            0
PTID           0
VISCODE        0
SITE           0
COLPROT        0
            ...
AV45.bl     6705
Years.bl       0
Month.bl       0
Month          2
M              0
Length: 89, dtype: int64

In [3]:
df_csf_biomarkers=pd.read_csv('../Dataset/csf_biomarkers.csv')
df_csf_biomarkers

,RID,dataset,ORIGPROT,VISCODE,ABETA,TAU,PTAU,RUNDATE,COLPROT,SITEID,USERDATE,USERDATE2,ABETA.RAW,TAU.RAW,PTAU.RAW,EXAMDATE
0,3,1,ADNI1,bl,131.0,68.0,21.0,NaN,ADNI1,107.0,2009-04-14,2009-09-27,NaN,NaN,NaN,NaN
1,4,1,ADNI1,bl,256.0,42.0,13.0,NaN,ADNI1,10.0,2009-04-14,2009-09-27,NaN,NaN,NaN,NaN
2,5,1,ADNI1,bl,115.0,112.0,68.0,NaN,ADNI1,107.0,2009-04-14,2009-09-27,NaN,NaN,NaN,NaN
3,8,1,ADNI1,bl,276.0,124.0,31.0,NaN,ADNI1,107.0,2009-04-14,2009-09-27,NaN,NaN,NaN,NaN
4,10,1,ADNI1,bl,88.0,135.0,29.0,NaN,ADNI1,107.0,2009-04-14,2009-09-27,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1108,5070,6,ADNI2,bl,107.6,64.2,62.5,2013-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-02-21
1109,5078,6,ADNI2,bl,177.4,42.1,13.7,2013-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-03-06
1110,5082,6,ADNI2,bl,200.9,48.0,14.2,2013-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-03-01
1111,5083,6,ADNI2,bl,148.8,64.7,19.2,2013-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-03-11
1112,5087,6,ADNI2,bl,119.6,194.5,145.5,2013-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-03-08

In [6]:
df_csf_biomarkers.columns

Index(['RID', 'dataset', 'ORIGPROT', 'VISCODE', 'ABETA', 'TAU', 'PTAU',
       'RUNDATE', 'COLPROT', 'SITEID', 'USERDATE', 'USERDATE2', 'ABETA.RAW',
       'TAU.RAW', 'PTAU.RAW', 'EXAMDATE'],
      dtype='object')

In [9]:
df_csf_biomarkers.dtypes

RID            int64
dataset        int64
ORIGPROT      object
VISCODE       object
ABETA        float64
TAU          float64
PTAU         float64
RUNDATE       object
COLPROT       object
SITEID       float64
USERDATE      object
USERDATE2     object
ABETA.RAW    float64
TAU.RAW      float64
PTAU.RAW     float64
EXAMDATE      object
dtype: object

In [11]:
df_csf_biomarkers.describe()

,RID,dataset,ABETA,TAU,PTAU,SITEID,ABETA.RAW,TAU.RAW,PTAU.RAW
count,1113.000000,1113.000000,1111.000000,1076.000000,1110.000000,415.000000,388.000000,381.000000,387.000000
mean,2826.731357,3.786164,172.096670,92.403067,38.909279,57.412048,239.450773,73.954593,24.250388
std,1839.916037,2.185035,54.312185,55.182944,23.013228,45.156211,78.333431,42.196958,12.150691
min,3.000000,1.000000,40.500000,17.700000,6.900000,1.000000,92.100000,20.300000,8.500000
25%,880.000000,1.000000,129.800000,52.875000,22.000000,14.000000,174.550000,44.700000,15.600000
50%,4037.000000,5.000000,158.100000,77.750000,34.050000,45.000000,237.550000,60.800000,21.100000
75%,4508.000000,6.000000,215.750000,116.000000,49.000000,108.000000,300.100000,91.600000,29.600000
max,5087.000000,6.000000,313.600000,495.000000,183.100000,127.000000,453.000000,270.800000,94.400000

In [15]:
df_csf_biomarkers.isnull().sum()

RID            0
dataset        0
ORIGPROT       0
VISCODE        0
ABETA          2
TAU           37
PTAU           3
RUNDATE      415
COLPROT      698
SITEID       698
USERDATE     698
USERDATE2    698
ABETA.RAW    725
TAU.RAW      732
PTAU.RAW     726
EXAMDATE     804
dtype: int64