In [1]:
import pandas as pd

In [2]:
df_csf_biomarkers=pd.read_csv('../Dataset/csf_biomarkers.csv')
df_csf_biomarkers

,RID,dataset,ORIGPROT,VISCODE,ABETA,TAU,PTAU,RUNDATE,COLPROT,SITEID,USERDATE,USERDATE2,ABETA.RAW,TAU.RAW,PTAU.RAW,EXAMDATE
0,3,1,ADNI1,bl,131.0,68.0,21.0,NaN,ADNI1,107.0,2009-04-14,2009-09-27,NaN,NaN,NaN,NaN
1,4,1,ADNI1,bl,256.0,42.0,13.0,NaN,ADNI1,10.0,2009-04-14,2009-09-27,NaN,NaN,NaN,NaN
2,5,1,ADNI1,bl,115.0,112.0,68.0,NaN,ADNI1,107.0,2009-04-14,2009-09-27,NaN,NaN,NaN,NaN
3,8,1,ADNI1,bl,276.0,124.0,31.0,NaN,ADNI1,107.0,2009-04-14,2009-09-27,NaN,NaN,NaN,NaN
4,10,1,ADNI1,bl,88.0,135.0,29.0,NaN,ADNI1,107.0,2009-04-14,2009-09-27,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1108,5070,6,ADNI2,bl,107.6,64.2,62.5,2013-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-02-21
1109,5078,6,ADNI2,bl,177.4,42.1,13.7,2013-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-03-06
1110,5082,6,ADNI2,bl,200.9,48.0,14.2,2013-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-03-01
1111,5083,6,ADNI2,bl,148.8,64.7,19.2,2013-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-03-11
1112,5087,6,ADNI2,bl,119.6,194.5,145.5,2013-03-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-03-08

In [3]:
df_csf_biomarkers.columns

Index(['RID', 'dataset', 'ORIGPROT', 'VISCODE', 'ABETA', 'TAU', 'PTAU',
       'RUNDATE', 'COLPROT', 'SITEID', 'USERDATE', 'USERDATE2', 'ABETA.RAW',
       'TAU.RAW', 'PTAU.RAW', 'EXAMDATE'],
      dtype='object')

In [4]:
df_csf_biomarkers.dtypes

RID            int64
dataset        int64
ORIGPROT      object
VISCODE       object
ABETA        float64
TAU          float64
PTAU         float64
RUNDATE       object
COLPROT       object
SITEID       float64
USERDATE      object
USERDATE2     object
ABETA.RAW    float64
TAU.RAW      float64
PTAU.RAW     float64
EXAMDATE      object
dtype: object

In [5]:
df_csf_biomarkers.describe()

,RID,dataset,ABETA,TAU,PTAU,SITEID,ABETA.RAW,TAU.RAW,PTAU.RAW
count,1113.000000,1113.000000,1111.000000,1076.000000,1110.000000,415.000000,388.000000,381.000000,387.000000
mean,2826.731357,3.786164,172.096670,92.403067,38.909279,57.412048,239.450773,73.954593,24.250388
std,1839.916037,2.185035,54.312185,55.182944,23.013228,45.156211,78.333431,42.196958,12.150691
min,3.000000,1.000000,40.500000,17.700000,6.900000,1.000000,92.100000,20.300000,8.500000
25%,880.000000,1.000000,129.800000,52.875000,22.000000,14.000000,174.550000,44.700000,15.600000
50%,4037.000000,5.000000,158.100000,77.750000,34.050000,45.000000,237.550000,60.800000,21.100000
75%,4508.000000,6.000000,215.750000,116.000000,49.000000,108.000000,300.100000,91.600000,29.600000
max,5087.000000,6.000000,313.600000,495.000000,183.100000,127.000000,453.000000,270.800000,94.400000

In [6]:
df_csf_biomarkers.isnull().sum()

RID            0
dataset        0
ORIGPROT       0
VISCODE        0
ABETA          2
TAU           37
PTAU           3
RUNDATE      415
COLPROT      698
SITEID       698
USERDATE     698
USERDATE2    698
ABETA.RAW    725
TAU.RAW      732
PTAU.RAW     726
EXAMDATE     804
dtype: int64